# use vi in copy mode
set-window-option -g mode-keys vi

# use zsh as default shell
set-option -g default-shell /bin/zsh

# remap prefix to Control + a
set -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix
unbind C-b
